# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build a release build"
  lane :release do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    match(type: "appstore")
    build_app(workspace: "Runner.xcworkspace", export_method: "app-store", clean: true)
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY"],
      in_house: false
    )
    setup_ci if ENV['CI']
    match(type: "appstore")
    build_app(workspace: "Runner.xcworkspace", export_method: "app-store", clean: true)
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end