# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
    "iPhone 16 Pro",
    # "iPhone 16 Pro Max",
    # "iPhone 16",
    # "iPhone 15",
    # "iPhone SE (3rd generation)",
    # "iPad Pro 11-inch (M4)",
    # "iPad Pro 13-inch (M4)",
    # "iPad mini (A17 Pro)"
])

languages([
    "en-US",
])

ios_version("18.2")

scheme("FastlaneSnapshot")

output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
